version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: blog
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3306:3306
