version: '3'

services:
  postgres:
    image: postgres:16.4-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESS_DB: auth