version: "3"

services:
  mongo:
    build:
      context: .
      args:
        MONGO_VERSION: 4.4-bionic
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: netflix
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: mongo
    ports:
      - 27017:27017
