version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: amigo_secreto
    # ports:
    #   - 5432:5432
    # volumes:
    #   - .:/var/lib/my_data
