version: '3'

services:
  postgres:
    image: postgres:14.13-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESS_DB: auth